# Generated by Django 4.2.16 on 2024-12-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
