# Generated by Django 4.2.16 on 2024-12-12 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_menuitem_menusection_delete_recipes_menuitem_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
    ]
