# Generated by Django 4.2.16 on 2025-02-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
